version: "2.4"
services: 

  influxdb:
    container_name: influxdb
    build: .  
    image: influxdb:latest
    networks:      
      - proxy-redirect
    ports:
      - "8086:8086"
    expose:
        - "8086"    
    restart: on-failure
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_USER=root
      - INFLUX_PASSWORD=root      
    mem_limit: 200m
        
networks: 
  proxy-redirect:
      name: proxy-redirect

